spring.datasource.url=jdbc:postgresql://localhost:5432/train_db
spring.datasource.username=postgres
spring.datasource.password=9553626268@As

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
